name: wvsu_attendance_system
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Formatting
  table_calendar: ^3.1.2
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  
  # Charts for Dashboard
  fl_chart: ^0.66.0
  
  # Networking (Used for API calls to PHP)
  http: ^1.2.0
  
  # File Handling (For importing students)
  file_picker: ^6.1.1
  excel: ^4.0.0
  csv: ^6.0.0
  pdf: ^3.10.8
  printing: ^5.12.0
  
  # Audio Playback for Scanner
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/blue_bg.png
    - assets/wvsu_logo.png
    - assets/attendance.png
    - assets/analytics.png
    - assets/dashboard.png
    - assets/imageTwo.png
    - assets/logout.png
    - assets/Rectangle.jpg
    - assets/useradd.png
    - assets/import.png
    - assets/acadsetup.png
    # Scanner Audio Files
    - assets/audio/inout.wav
    - assets/audio/wrong.wav

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700